-- =========================================================
-- SISTEM KUPON QR ONLINE
-- Jalankan seluruh file ini di Supabase SQL Editor.
-- =========================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------
-- TABEL BLOK
-- ---------------------------------------------------------
create table if not exists public.allowed_blocks (
  id bigint generated by default as identity primary key,
  block text not null unique,
  created_at timestamptz not null default now()
);

insert into public.allowed_blocks (block)
values ('B3'), ('B4'), ('B5'), ('B7')
on conflict (block) do nothing;

-- ---------------------------------------------------------
-- TABEL KUPON
-- token adalah kode acak yang dipakai di URL/QR.
-- code_address tetap unik berdasarkan blok + nomor rumah.
-- ---------------------------------------------------------
create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  block text not null,
  house_no text not null,
  code_address text generated always as (upper(trim(block)) || '-' || upper(trim(house_no))) stored,
  token text not null unique default encode(gen_random_bytes(12), 'hex'),
  used boolean not null default false,
  created_at timestamptz not null default now(),
  used_at timestamptz
);

create unique index if not exists one_coupon_per_address
on public.coupons (upper(trim(block)), upper(trim(house_no)));

create index if not exists coupons_token_idx on public.coupons(token);
create index if not exists coupons_used_idx on public.coupons(used);

-- ---------------------------------------------------------
-- TABEL SCAN
-- ---------------------------------------------------------
create table if not exists public.scans (
  id bigint generated by default as identity primary key,
  coupon_id uuid not null references public.coupons(id) on delete cascade,
  scanned_at timestamptz not null default now(),
  scanned_by uuid references auth.users(id)
);

create index if not exists scans_coupon_idx on public.scans(coupon_id);

-- ---------------------------------------------------------
-- RLS
-- ---------------------------------------------------------
alter table public.allowed_blocks enable row level security;
alter table public.coupons enable row level security;
alter table public.scans enable row level security;

drop policy if exists "authenticated read allowed blocks" on public.allowed_blocks;
create policy "authenticated read allowed blocks"
on public.allowed_blocks for select
to authenticated
using (true);

drop policy if exists "authenticated manage allowed blocks" on public.allowed_blocks;
create policy "authenticated manage allowed blocks"
on public.allowed_blocks for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated read coupons" on public.coupons;
create policy "authenticated read coupons"
on public.coupons for select
to authenticated
using (true);

drop policy if exists "authenticated insert coupons" on public.coupons;
create policy "authenticated insert coupons"
on public.coupons for insert
to authenticated
with check (
  exists (
    select 1 from public.allowed_blocks b
    where upper(b.block) = upper(trim(block))
  )
);

drop policy if exists "authenticated read scans" on public.scans;
create policy "authenticated read scans"
on public.scans for select
to authenticated
using (true);

-- ---------------------------------------------------------
-- PUBLIC LOOKUP
-- Penerima hanya perlu token. Fungsi hanya mengembalikan
-- data minimal yang diperlukan untuk menampilkan QR.
-- ---------------------------------------------------------
create or replace function public.get_public_coupon(p_token text)
returns table (
  name text,
  block text,
  house_no text,
  code_address text,
  token text,
  used boolean
)
language sql
security definer
set search_path = public
as $$
  select c.name, c.block, c.house_no, c.code_address, c.token, c.used
  from public.coupons c
  where c.token = trim(p_token)
  limit 1;
$$;

revoke all on function public.get_public_coupon(text) from public;
grant execute on function public.get_public_coupon(text) to anon, authenticated;

-- ---------------------------------------------------------
-- ATOMIC REDEEM
-- Hanya kupon yang belum digunakan yang dapat diubah.
-- Jika sudah digunakan, returns ok=false.
-- ---------------------------------------------------------
create or replace function public.redeem_coupon(p_token text)
returns table (
  ok boolean,
  reason text,
  coupon_id uuid,
  coupon_name text,
  code_address text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  c public.coupons%rowtype;
  v_user uuid := auth.uid();
begin
  select *
  into c
  from public.coupons
  where token = trim(p_token)
  for update;

  if not found then
    return query select false, 'NOT_FOUND', null::uuid, null::text, null::text;
    return;
  end if;

  if c.used then
    return query select false, 'ALREADY_USED', c.id, c.name, c.code_address;
    return;
  end if;

  update public.coupons
  set used = true, used_at = now()
  where id = c.id;

  insert into public.scans(coupon_id, scanned_by)
  values(c.id, v_user);

  return query select true, 'REDEEMED', c.id, c.name, c.code_address;
end;
$$;

revoke all on function public.redeem_coupon(text) from public;
grant execute on function public.redeem_coupon(text) to authenticated;
